language: python

python:
  - "3.7-dev"

install:
  - pip install pipenv
  - pipenv install
  - pipenv shell
script:
  - pytest
  - sonar-scanner -Dsonar.projectKey=symonk_pylenium  -Dsonar.organization=symonk-github
  -
branches:
  only:
  - master
  -
git:
  depth: 99999

before_install:
- export CHROME_BIN=/usr/bin/google-chrome

cache:
  directories:
  - "$HOME/.sonar/cache"
  -
addons:
  apt:
    update: true
  chrome: stable
  sonarcloud:
    organization: symonk-github

packages:
  - google-chrome-stable
