language: python
dist: xenial
python: 3.7

install:
  - pip install pipenv
  - pipenv install
  - pipenv sync
script:
  - python -m http.server & # integration server
  - pytest -m IT --cov-report term --cov=./
  - sonar-scanner -Dsonar.projectKey=symonk_pylenium  -Dsonar.organization=symonk-github
branches:
  only:
    - master
git:
  depth: 99999

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome

cache:
  directories:
    - "$HOME/.sonar/cache"
    -
addons:
  apt:
    update: true
  chrome: stable
  sonarcloud:
    organization: symonk-github

packages:
  - google-chrome-stable

env:
  pylenium_headless=true
  pylenium_base_url = 'http://localhost:8000/tests/server/static_content/'

after_success:
  - codecov
