language: python
python:
  - "3.7-dev"

# command to install dependencies
install:
  - pip install pipenv
  - pipenv install

script:
  - pytest

branches:
  only:
  - master
git:
  depth: 99999

before_install:
- export CHROME_BIN=/usr/bin/google-chrome


cache:
  directories:
  - "$HOME/.sonar/cache"

addons:
  apt:
    update: true
  chrome: stable

packages:
  - google-chrome-stable